# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install -t pre-commit -t pre-push

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/packit/pre-commit-hooks
    rev: a0ee4e8abebda41b5c2420a98d8251296df89e54
    hooks:
      - id: check-rebase
        args:
          - git://github.com/packit/contributing.git
        stages: [manual, push]
