# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install -t pre-commit -t pre-push

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/packit/pre-commit-hooks
    rev: 9b169f07b6400eb73ed5e5d6d28eb0d9280031b3
    hooks:
      - id: check-rebase
        args:
          - git://github.com/packit/contributing.git
        stages: [manual, push]
